import { defineConfig, devices } from '@playwright/test';

// Firstmate Playwright QA harness - generated by fm-playwright-scaffold.sh.
// Headless and isolated by default: Playwright launches its own bundled
// Chromium in a fresh, throwaway browser context and never attaches to the
// captain's real Chrome profile. Each named project pins an exact viewport so
// screenshots are deterministic, comparable visual evidence.
export default defineConfig({
  testDir: './qa/specs',
  outputDir: './qa/results',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: process.env.CI ? [['github'], ['list']] : [['list']],
  use: {
    headless: true,
    screenshot: 'only-on-failure',
    trace: 'on-first-retry',
  },
  projects: [
    { name: 'desktop-1857x933', use: { ...devices['Desktop Chrome'], viewport: { width: 1857, height: 933 } } },
    { name: 'laptop-1440x900', use: { ...devices['Desktop Chrome'], viewport: { width: 1440, height: 900 } } },
  ],
});
