defaultPlacement: end
fieldLayouts:
  67ac1295-90bc-41b7-90fe-b80831dfab97:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-10T19:06:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: b2906ffc-cfe5-421c-a953-4930b666af8a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T19:06:33+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: f301813d-262f-49d6-a891-3384e9bcd3b3
            userCondition: null
            warning: null
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-03-27T18:26:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 2aea3e16-f8d4-4dec-bfc9-098a9aec2032
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-03-27T18:26:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: c332e1d1-462b-4e8d-b895-b8263c09394c
            userCondition: null
            warning: null
            width: 100
          -
            attribute: newWindow
            dateAdded: '2025-03-27T18:26:57+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 3d666e90-40bb-40b9-95dc-ad8c61440ee3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T10:44:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6df9eae6-a3ee-40e7-a01d-82706df88b3e # Speedbump
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a05bd292-7568-4008-bd72-52837a0db3c0
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2025-03-27T18:26:57+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: e1b99cd6-75f0-4217-a5cd-a123fde1952d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ea51dbd1-0d54-458e-9282-233e50dc38ce
        userCondition: null
handle: footerSubNavigation
instructions: ''
maxNodes: null
name: 'Footer Sub Navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\supertable\elements\SuperTableBlockElement:
    enabled: ''
    permissions: '*'
propagationMethod: all
siteSettings:
  a57193b9-dd25-415d-a670-e4b6a0c7b8cb: # $SYSTEM_NAME
    enabled: true
sortOrder: 4
structure:
  maxLevels: null
  uid: 2ae43834-364d-409f-9455-3149fb388b33
