#!/usr/bin/env bash
# Behavioral regressions for ask-user authority instructions generated by fm-brief.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

BRIEF="$ROOT/bin/fm-brief.sh"
TMP_ROOT=$(fm_test_tmproot fm-ask-user-authority)

test_primary_and_secondmate_instruction_generation() {
  local home ship charter
  home="$TMP_ROOT/home"
  mkdir -p "$home/data"

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" \
    "$BRIEF" authority-worker sample --mode no-mistakes >/dev/null 2>&1
  ship="$home/data/authority-worker/brief.md"
  assert_grep 'ask-user findings are never yours to answer' "$ship" \
    "generated implementation brief lets the worker own an ask-user decision"
  assert_grep "The repository owner applies \`ask-user-authority\` and obtains any required decision" "$ship" \
    "generated implementation brief bypasses the primary authority owner"
  assert_grep "silently bypass firstmate's authority check and any required captain escalation" "$ship" \
    "generated implementation brief permits silent ask-user auto-resolution"
  assert_no_grep 'the captain, not you, owns the ask-user decisions' "$ship" \
    "generated implementation brief retained conflicting captain-only wording"

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" FM_SECONDMATE_CHARTER='Handle sample work.' \
    "$BRIEF" authority-mate --secondmate --no-projects >/dev/null 2>&1
  charter="$home/data/authority-mate/brief.md"
  # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
  assert_grep 'The local `AGENTS.md` is your job description' "$charter" \
    "generated secondmate charter does not load the tracked authority boundary"
  assert_no_grep 'continuous frame-by-frame monitoring' "$charter" \
    "generated secondmate charter duplicated the detailed authority procedure"
  pass "primary workers and secondmates receive the authority rule through generated instructions"
}

# The ask-user escalation cites the needs-decision rule by number, so any
# renumbering of the Rules block must move the citation with it or the worker is
# sent to the wrong rule.
test_ask_user_escalation_cites_the_needs_decision_rule() {
  local home ship pointer
  home="$TMP_ROOT/pointer-home"
  mkdir -p "$home/data"

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" \
    "$BRIEF" pointer-worker sample --mode no-mistakes >/dev/null 2>&1
  ship="$home/data/pointer-worker/brief.md"
  pointer=$(sed -n 's/.*escalate to firstmate (rule \([0-9][0-9]*\)).*/\1/p' "$ship")
  [ -n "$pointer" ] || fail "generated implementation brief lost the numbered ask-user escalation target"
  grep -q "^$pointer\. If a decision belongs above the implementation worker" "$ship" \
    || fail "ask-user escalation cites rule $pointer, which is not the needs-decision rule"
  pass "ask-user escalation cites the needs-decision rule number"
}

test_primary_and_secondmate_instruction_generation
test_ask_user_escalation_cites_the_needs_decision_rule
