#!/usr/bin/env bash
# shellcheck disable=SC2016
# Behavior tests for bin/fm-attribution-pretool-check.sh, the matcher that
# refuses AI self-attribution in a worker's commits and PRs, for the task
# worktree commit-msg hook that runs it on every harness, and for its wiring
# into a claude task worker's worktree PreToolUse hooks by bin/fm-spawn.sh.
#
# No harness is spawned: the guard is driven with Claude-shaped payloads, and
# the spawn cases run the real fm-spawn against a fake tmux pane, then run the
# exact PreToolUse command it registered and make real git commits in the task
# worktree, its primary checkout, and a sibling worktree. The live proof that
# real Claude Code is refused is tests/fm-attribution-guard-live-e2e.test.sh.
set -u

# shellcheck source=tests/fixtures.sh
. "$(dirname "${BASH_SOURCE[0]}")/fixtures.sh"

TMP_ROOT=$(fm_test_tmproot fm-attribution-pretool-check)
GUARD="$ROOT/bin/fm-attribution-pretool-check.sh"

payload() {  # <command> [cwd]
  jq -cn --arg c "$1" --arg d "${2:-}" \
    '{hook_event_name:"PreToolUse",tool_name:"Bash",tool_input:{command:$c}} + (if $d == "" then {} else {cwd:$d} end)'
}

guard_code() {  # <command> [cwd] -> prints the guard's exit status
  local rc
  payload "$@" | "$GUARD" >/dev/null 2>&1
  rc=$?
  printf '%s\n' "$rc"
}

expect_deny() {  # <command> <why>
  assert_equals 2 "$(guard_code "$1")" "guard did not deny: $2"
}

expect_allow() {  # <command> <why>
  assert_equals 0 "$(guard_code "$1")" "guard did not allow: $2"
}

test_denies_attributed_commit_and_pr_commands() {
  expect_deny $'git commit -m "fix: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>"' \
    "the exact trailer a real worker commit carried"
  expect_deny $'git commit -m "$(cat <<EOF\nfix\n\nCo-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>\nEOF\n)"' \
    "a heredoc commit message naming a Claude model"
  expect_deny $'git -C /some/where commit --amend -m "a\n\nco-authored-by: Codex <codex@openai.com>"' \
    "a lower-case trailer naming another AI through git -C"
  expect_deny $'git commit -m "a\n\nCo-Authored-By: Claude"' "a bare Claude trailer at the end of the message"
  expect_deny $'gh pr create --title x --body "stuff\n\n\xf0\x9f\xa4\x96 Generated with [Claude Code](https://claude.com/claude-code)"' \
    "a Generated with line in a PR body"
  expect_deny $'gh pr create --title t --body $\'## Summary\\n- x\\n\\n\xf0\x9f\xa4\x96 Generated with [Claude Code](https://claude.com/claude-code)\'' \
    "a Generated with line after escaped newlines in an ANSI-C quoted PR body"
  expect_deny 'gh pr create --title t --body "x\r\nGenerated with Claude Code"' \
    "a Generated with line after an escaped CRLF in a double-quoted PR body"
  expect_deny 'gh-axi pr edit 12 --body "see https://claude.ai/code/session_abc"' "a Claude session link through gh-axi"
  expect_deny $'git commit -m "x\n\nClaude-Session: abc"' "a Claude-Session trailer"
  pass "attributed commit and PR commands are denied"
}

test_allows_human_messages_and_reads() {
  expect_allow 'git commit -m "fix: a plain message"' "an ordinary commit"
  expect_allow $'git commit -m "a\n\nCo-Authored-By: Claude Dupont <claude@example.fr>"' "a human co-author named Claude"
  expect_allow $'git commit -m "a\n\nCo-Authored-By: Brian Aiken <brian@example.com>"' "a human whose name contains 'an ai'"
  expect_allow $'git commit -m "a\n\nCo-authored-by: Jean-Claude <jc@example.fr>"' "a human co-author whose name ends in Claude"
  expect_deny $'git commit -m "a\n\nCo-authored-by: Jean-Claude <noreply@anthropic.com>"' "a Claude-like name with a vendor address"
  expect_allow 'git commit -m "fix(bin): parse the JSON generated by codex exec"' "a subject naming codex output"
  expect_allow 'git commit -m "feat: handle output generated by gemini 2.5"' "a subject naming gemini output"
  expect_allow 'git commit -m "docs: note fixtures are generated with an AI-free script"' "a subject naming a generator"
  expect_allow $'git commit -m "a\n\nCo-authored-by: Devin Smith <devin@example.com>"' "a human co-author named Devin"
  expect_allow $'git commit -m "a\n\nCo-authored-by: Kimi Raikkonen <k@example.fi>"' "a human co-author named Kimi"
  expect_allow $'git commit -m "a\n\nCo-authored-by: Gemini Grok <gg@example.org>"' "a human co-author with agent-like names"
  expect_deny $'git commit -m "a\n\nCo-authored-by: devin-ai-integration[bot] <158243242+devin-ai-integration[bot]@users.noreply.github.com>"' \
    "Devin's bot account"
  expect_deny $'git commit -m "a\n\nCo-authored-by: Cursor Agent <cursoragent@cursor.com>"' "Cursor's agent address"
  expect_deny $'git commit -m "a\n\nCo-authored-by: Gemini CLI <gemini@example.com>"' "a Gemini product qualifier"
  expect_allow 'gh pr list --search "Generated with Claude Code"' "a gh pr search that quotes the pattern"
  expect_allow 'gh pr view 12 --json body | grep -ci "co-authored-by: claude <x>"' "a gh pr read piped into a search"
  expect_allow 'gh api -X GET search/issues -f q="Generated with Claude Code"' "a GET gh api search with fields"
  expect_allow 'gh api repos/o/r/pulls/1 --jq ".body" | grep "Generated with Claude Code"' "a plain GET gh api read"
  expect_deny 'gh -R o/r pr create --title t --body "Generated with Claude Code"' "a gh pr create after -R"
  expect_deny 'gh api -X PATCH repos/o/r/pulls/1 --input body.json -f body="Generated with Claude Code"' "a PATCH gh api write"
  expect_deny 'gh-axi api repos/o/r/issues/1/comments -f body="Generated with Claude Code"' "a gh api field write with the default POST"
  expect_deny $'gh api repos/o/r/pulls/1 -f body="to read, pass -X GET.\n\nGenerated with Claude Code"' \
    "a default-POST gh api write whose quoted body mentions -X GET"
  expect_deny 'gh api -X GET --method PATCH repos/o/r/pulls/1 -f body="Generated with Claude Code"' \
    "a gh api call naming any non-GET method"
  expect_allow 'git log --format=%B | grep -i "Co-Authored-By: Claude"' "searching history for the pattern"
  expect_allow 'grep -rn "Co-Authored-By: Claude" docs' "grepping for the pattern outside git"
  expect_allow 'echo "Co-Authored-By: Claude <noreply@anthropic.com>" > notes.txt' "a command that writes no commit or PR"
  expect_allow 'git log --oneline --grep="Co-Authored-By: Claude <x>" | grep merge' "a git read whose pipeline names a writing verb"
  expect_allow 'echo "git commit" | grep -c "Co-Authored-By: Claude <x>"' "a writing verb that is only an argument"
  expect_deny $'cd /repo && git -c user.name=x --no-pager commit -m "a\n\nCo-Authored-By: Claude <x>"' \
    "a commit after a separator and git global options"
  expect_deny $'/usr/bin/git tag -a v1 -m "Generated with Claude Code"' "a tag through an absolute git path"
  pass "human-written messages and read-only searches are allowed"
}

test_scans_message_files_the_command_names() {
  local dir=$TMP_ROOT/files
  mkdir -p "$dir"
  printf 'fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n' >"$dir/msg.txt"
  printf 'fix: plain\n' >"$dir/clean.txt"
  expect_deny "git commit -F $dir/msg.txt" "an attributed message file passed to -F"
  expect_deny "gh pr create --title t --body-file=$dir/msg.txt" "an attributed --body-file=path"
  printf 'fix\n\nGenerated with [Claude Code](https://claude.com/claude-code)\n' >"$dir/body.md"
  expect_allow "git commit -F $dir/clean.txt" "a clean message file"
  expect_deny "git commit --file=$dir/msg.txt" "an attributed --file=path"
  expect_deny "gh pr create -t t -F $dir/body.md" "an attributed gh -F body file"
  expect_deny "gh api repos/o/r/pulls -f title=t --field body=@$dir/body.md" "an attributed gh api body=@file field"
  expect_allow "git add $dir/msg.txt && git commit -m 'docs: refresh verification notes'" \
    "a clean message alongside a staged file that quotes the pattern"
  expect_allow "git commit $dir/msg.txt -m 'docs: plain'" "a clean message with a pathspec that quotes the pattern"
  assert_equals 2 "$(guard_code 'git commit -F msg.txt' "$dir")" \
    "a relative message file was not resolved from the payload cwd"
  pass "message files named by the command are scanned, relative to the payload cwd"
}

test_transport_edges() {
  local out rc
  out=$(printf '' | "$GUARD" 2>&1)
  rc=$?
  expect_code 0 "$rc" "empty stdin must allow"
  printf 'not json: git commit -m "x Co-Authored-By: Claude <x>"' | "$GUARD" >/dev/null 2>&1
  expect_code 2 $? "unparsable stdin must be scanned as raw text rather than allowed"
  out=$("$GUARD" --command $'git commit -m "x\n\nCo-Authored-By: Claude <noreply@anthropic.com>"' 2>&1)
  rc=$?
  expect_code 2 "$rc" "--command mode must deny an attributed commit"
  assert_contains "$out" "Remove these lines and try again" "the denial did not tell the model how to recover"
  assert_contains "$out" "Co-Authored-By: Claude <noreply@anthropic.com>" "the denial did not name the line to remove"
  out=$(payload $'git commit -m "x\n\nCo-Authored-By: Claude <a@b>"' | "$GUARD" 2>/dev/null)
  [ -z "$out" ] || fail "a denial must keep stdout empty for Claude, got: $out"
  pass "empty, unparsable, and --command inputs behave as documented"
}

test_message_file_mode() {
  local dir=$TMP_ROOT/msgmode out
  mkdir -p "$dir"
  printf 'fix: x\n\nCo-authored-by: Claude Sonnet 4 <noreply@anthropic.com>\n' >"$dir/bad"
  printf 'fix: x\n# ------------------------ >8 ------------------------\n+Co-Authored-By: Claude <x>\n' >"$dir/verbose"
  out=$("$GUARD" --message-file "$dir/bad" 2>&1)
  expect_code 2 $? "--message-file must reject an attributed message"
  assert_contains "$out" "Co-authored-by: Claude Sonnet 4 <noreply@anthropic.com>" "the rejection did not name the line to remove"
  printf 'fix(bin): parse the JSON generated by codex exec\n\nCo-authored-by: Jean-Claude <jc@example.fr>\n' >"$dir/human"
  "$GUARD" --message-file "$dir/human" >/dev/null 2>&1
  expect_code 0 $? "a subject naming generated output and a human Jean-Claude are not attribution"
  printf 'fix: x\n\n**Generated by Codex CLI**\n' >"$dir/footer"
  "$GUARD" --message-file "$dir/footer" >/dev/null 2>&1
  expect_code 2 $? "a Generated by footer line is attribution"
  "$GUARD" --message-file "$dir/verbose" >/dev/null 2>&1
  expect_code 0 $? "a diff below the scissors line of git commit -v is not the message"
  "$GUARD" --message-file "$dir/missing" >/dev/null 2>&1
  expect_code 0 $? "a missing message file has nothing to reject"
  pass "--message-file rejects an attributed commit message and names what to remove"
}

test_claude_spawn_registers_the_guard() {
  local case_dir=$TMP_ROOT/spawn home proj wt fakebin out settings cmd rc id=attr-cl-1
  home="$case_dir/home"
  proj="$case_dir/project"
  wt="$case_dir/wt"
  fakebin=$(make_spawn_fakebin "$case_dir/fake" claude)
  fm_test_spawn_home "$home" claude
  fm_git_worktree "$proj" "$wt" wt-attr
  fm_test_spawn_brief "$home" "$id"
  out=$(fm_test_run_spawn "$home" "$wt" "$fakebin" "$id" "$proj" --mode no-mistakes --yolo off)
  expect_code 0 $? "claude spawn should succeed: $out"
  settings="$wt/.claude/settings.local.json"
  assert_present "$settings" "claude spawn wrote no worktree hook settings"
  assert_equals Bash "$(jq -r '.hooks.PreToolUse[0].matcher' "$settings")" "the guard is not scoped to the Bash tool"
  cmd=$(jq -r '.hooks.PreToolUse[0].hooks[0].command' "$settings")
  [ -n "$cmd" ] && [ "$cmd" != null ] || fail "claude spawn registered no PreToolUse hook command"
  payload $'git commit -m "x\n\nCo-Authored-By: Claude <noreply@anthropic.com>"' | sh -c "$cmd" >/dev/null 2>&1
  rc=$?
  expect_code 2 "$rc" "the registered hook command did not deny an attributed commit"
  payload 'git commit -m "x"' | sh -c "$cmd" >/dev/null 2>&1
  expect_code 0 $? "the registered hook command denied a clean commit"
  pass "a claude task spawn registers the attribution guard as a Bash PreToolUse hook"
}

test_denies_attributed_commit_and_pr_commands
test_allows_human_messages_and_reads
test_scans_message_files_the_command_names
test_transport_edges
test_message_file_mode
test_claude_spawn_registers_the_guard
