#!/usr/bin/env bash
# Behavioral regressions for ask-user authority instructions generated by fm-brief.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

BRIEF="$ROOT/bin/fm-brief.sh"
TMP_ROOT=$(fm_test_tmproot fm-ask-user-authority)

test_primary_and_secondmate_instruction_generation() {
  local home ship charter
  home="$TMP_ROOT/home"
  mkdir -p "$home/data"

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" \
    "$BRIEF" authority-worker sample --mode no-mistakes >/dev/null 2>&1
  ship="$home/data/authority-worker/brief.md"
  assert_grep 'ask-user findings are never yours to answer' "$ship" \
    "generated implementation brief lets the worker own an ask-user decision"
  assert_grep "Firstmate applies \`ask-user-authority\` and obtains any required captain decision" "$ship" \
    "generated implementation brief bypasses the primary authority owner"
  # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
  assert_grep 'NEVER pass `--yes` (or `-y`) to `no-mistakes axi run` or `no-mistakes axi respond`' "$ship" \
    "generated implementation brief does not prohibit silent ask-user auto-resolution"
  assert_grep 'It auto-resolves every gate including ask-user findings with no escalation' "$ship" \
    "generated implementation brief does not explain the ask-user authority bypass"
  assert_no_grep 'the captain, not you, owns the ask-user decisions' "$ship" \
    "generated implementation brief retained conflicting captain-only wording"
  # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
  assert_grep 'Fix rounds are capped at three per run, counted as your own `no-mistakes axi respond --action fix` responses' "$ship" \
    "generated implementation brief leaves the cap without an observable counting unit"
  assert_grep 'approve past wording, restatement, simplification, and documentation-polish findings even when the reviewer is right, unless the text is actually false' "$ship" \
    "generated implementation brief withholds the proportionality criterion from the worker that drives auto-fix gates"
  assert_grep 'The count is advisory rather than enforced' "$ship" \
    "generated implementation brief presents the advisory count as an enforced limit"
  assert_grep 'Once you have sent three, escalate the next gate to firstmate' "$ship" \
    "generated implementation brief does not make the worker stop at the cap"
  assert_no_grep 'not a correctness or contract defect' "$ship" \
    "generated implementation brief restated the post-cap sorting criteria the skill owns"

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" FM_SECONDMATE_CHARTER='Handle sample work.' \
    "$BRIEF" authority-mate --secondmate --no-projects >/dev/null 2>&1
  charter="$home/data/authority-mate/brief.md"
  # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
  assert_grep 'The local `AGENTS.md` is your job description' "$charter" \
    "generated secondmate charter does not load the tracked authority boundary"
  assert_no_grep 'continuous frame-by-frame monitoring' "$charter" \
    "generated secondmate charter duplicated the detailed authority procedure"
  pass "primary workers and secondmates receive the authority rule through generated instructions"
}

test_primary_and_secondmate_instruction_generation
