#!/usr/bin/env bash
# Acceptance coverage for the nonterminal paused-status contract in ship and
# scout briefs generated by bin/fm-brief.sh.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

TMP_ROOT=$(fm_test_tmproot fm-brief-paused-nonterminal)
BRIEF_HOME="$TMP_ROOT/home"
mkdir -p "$BRIEF_HOME/data"

normalize_brief() {
  tr '\n' ' ' < "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[[:space:]][[:space:]]*/ /g'
}

assert_paused_guidance() {
  local kind=$1 brief=$2 verb=$3 text guidance marker tail ending_sentence ending_list token_count
  text=$(normalize_brief "$brief")
  marker="use \`$verb: {why}\`"
  assert_contains "$text" "$marker" \
    "$kind clause 1: pause guidance must name the configured '$verb:' status"

  guidance=${text#*"$marker"}
  guidance=${guidance%%" 5. if you hit"*}
  tail=$guidance
  assert_contains "$tail" "nonterminal" \
    "$kind clause 1: '$verb:' guidance must state that the status is nonterminal"
  tail=${tail#*"nonterminal"}
  assert_contains "$tail" "do not end the turn" \
    "$kind clause 1: '$verb:' guidance must say not to end the turn"
  tail=${tail#*"do not end the turn"}
  case "$tail" in
    *sleep*) tail=${tail#*sleep} ;;
    *poll*) tail=${tail#*poll} ;;
    *) fail "$kind clause 1: '$verb:' guidance must require an explicit in-turn sleep or poll" ;;
  esac
  assert_contains "$tail" "append \`resolved:\`" \
    "$kind clause 1: '$verb:' guidance must require appending 'resolved:' after the wait clears"

  ending_sentence=$(printf '%s\n' "$guidance" | sed 's/[.!?]/\
/g' | grep -i 'may end a turn' | head -n 1)
  assert_contains "$ending_sentence" "may end a turn" \
    "$kind clause 2: guidance must state which statuses may end a turn"
  ending_list=${ending_sentence%%"may end a turn"*}
  for terminal in needs-decision blocked "done" failed; do
    assert_contains "$ending_list" "\`$terminal:\`" \
      "$kind clause 2: may-end list must contain '$terminal:'"
  done
  token_count=$(printf '%s\n' "$ending_list" | grep -Eo "\`[a-z-]+:\`" | wc -l | tr -d ' ')
  expect_code 4 "$token_count" \
    "$kind clause 2: may-end list must contain exactly needs-decision, blocked, done, and failed"
  assert_not_contains "$ending_list" "\`working:\`" \
    "$kind clause 2: may-end list must not contain 'working:'"
  assert_not_contains "$ending_list" "\`$verb:\`" \
    "$kind clause 2: may-end list must not contain '$verb:'"
  assert_not_contains "$ending_list" "\`paused:\`" \
    "$kind clause 2: may-end list must not contain hard-coded 'paused:'"

  assert_contains "$text" \
    "a mid-task \`working:\` line (including setup complete) is nonterminal: do not end the turn after it; continue the same stage until a defined \`done:\` gate under definition of done." \
    "$kind clause 3: existing working-status nonterminal sentence changed"
}

generate_brief_pair() {
  local verb=$1 suffix=$2
  FM_HOME="$BRIEF_HOME" FM_CLASSIFY_PAUSED_VERB="$verb" \
    "$ROOT/bin/fm-brief.sh" "paused-ship-$suffix" firstmate --mode no-mistakes >/dev/null 2>&1 \
    || fail "ship fixture with '$verb:' did not scaffold"
  FM_HOME="$BRIEF_HOME" FM_CLASSIFY_PAUSED_VERB="$verb" \
    "$ROOT/bin/fm-brief.sh" "paused-scout-$suffix" firstmate --scout >/dev/null 2>&1 \
    || fail "scout fixture with '$verb:' did not scaffold"
}

generate_brief_pair paused default
assert_paused_guidance ship "$BRIEF_HOME/data/paused-ship-default/brief.md" paused
assert_paused_guidance scout "$BRIEF_HOME/data/paused-scout-default/brief.md" paused
pass "fm-brief paused contract: ship and scout waits are nonterminal and end-turn states are exact"

generate_brief_pair holding configured
assert_paused_guidance ship-configured "$BRIEF_HOME/data/paused-ship-configured/brief.md" holding
assert_paused_guidance scout-configured "$BRIEF_HOME/data/paused-scout-configured/brief.md" holding
assert_no_grep "\`paused:\`" "$BRIEF_HOME/data/paused-ship-configured/brief.md" \
  "ship clause 4: custom pause verb was hard-coded as 'paused:' in new guidance"
assert_no_grep "\`paused:\`" "$BRIEF_HOME/data/paused-scout-configured/brief.md" \
  "scout clause 4: custom pause verb was hard-coded as 'paused:' in new guidance"
pass "fm-brief paused contract: configured holding verb is substituted in ship and scout guidance"
