#!/usr/bin/env bash
# Behavior tests for the project output contract check: fleet terminology,
# agent self-attribution, and external tracker ids must not reach project text.
#
# These rules used to live only in data/captain.md, so they held only as long as
# the agent remembered them - and a harness may actively instruct an agent to add
# an attribution trailer. These tests pin the repository-side boundary that
# overrides such an instruction.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

CHECK="$ROOT/bin/fm-output-contract-check.sh"
TMP_ROOT=$(fm_test_tmproot fm-output-contract)

msg() {  # <name> <content...>
  local name=$1
  shift
  printf '%s\n' "$@" > "$TMP_ROOT/$name"
  printf '%s\n' "$TMP_ROOT/$name"
}

expect_reject() {  # <file> <needle> <why>
  local file=$1 needle=$2 why=$3 out status=0
  out=$("$CHECK" --message "$file" 2>&1) || status=$?
  expect_code 1 "$status" "$why (expected rejection)"
  assert_contains "$out" "$needle" "$why (wrong reason reported)"
}

expect_accept() {  # <file> <why>
  local file=$1 why=$2 status=0
  "$CHECK" --message "$file" >/dev/null 2>&1 || status=$?
  expect_code 0 "$status" "$why"
}

test_agent_coauthor_trailer_is_rejected() {
  expect_reject "$(msg trailer.txt 'fix: tidy the parser' '' \
    'Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>')" \
    "attribution trailer/footer is forbidden" \
    "a Claude co-author trailer must be rejected"
  expect_reject "$(msg trailer2.txt 'fix: thing' '' 'Co-authored-by: Codex <x@y>')" \
    "attribution trailer/footer is forbidden" \
    "a Codex co-author trailer must be rejected"
  pass "agent co-author trailers are rejected regardless of harness"
}

test_generated_by_footer_is_rejected() {
  expect_reject "$(msg footer.txt 'feat: add thing' '' \
    '🤖 Generated with [Claude Code](https://claude.com/claude-code)')" \
    "attribution trailer/footer is forbidden" \
    "the Claude Code footer must be rejected"
  expect_reject "$(msg footer2.txt 'feat: x' '' 'Generated by Codex')" \
    "attribution trailer/footer is forbidden" \
    "a Codex footer must be rejected"
  pass "agent attribution footers are rejected"
}

test_fleet_terminology_is_rejected() {
  local term
  for term in firstmate crewmate secondmate captain; do
    expect_reject "$(msg "fleet-$term.txt" "chore: work done by the $term")" \
      "fleet terminology" \
      "the term '$term' must not reach project output"
  done
  pass "fleet role vocabulary is rejected in project output"
}

test_tracker_ids_are_rejected() {
  expect_reject "$(msg tracker.txt 'fix: resolve CAN-42 edge case')" \
    "issue-tracker id" \
    "an external tracker id must not reach project output"
  pass "external issue-tracker ids are rejected"
}

test_ordinary_project_text_is_accepted() {
  expect_accept "$(msg clean.txt 'fix: correct the retry backoff' '' \
    'The parser retried too aggressively on 429 responses.' '' \
    'Reviewed-by: Guillermo Casanova <gcasanova@lucora.eu>')" \
    "ordinary project text with a human trailer must pass"
  pass "ordinary project text, including a human trailer, is accepted"
}

test_verdict_survives_the_pipeline() {
  # Regression: scan_stream is the last stage of a pipeline, which bash runs in
  # a subshell. An earlier draft set a flag there, so every check passed
  # silently. Proven through the range mode, which is pipeline-driven.
  local repo out status=0
  repo="$TMP_ROOT/repo"
  mkdir -p "$repo"
  git -C "$repo" init -q
  git -C "$repo" config user.email t@example.com
  git -C "$repo" config user.name Tester
  printf 'hello\n' > "$repo/a.txt"
  git -C "$repo" add a.txt
  git -C "$repo" commit -qm "initial"
  printf 'hello\nthe crewmate did it\n' > "$repo/a.txt"
  git -C "$repo" add a.txt
  git -C "$repo" commit -qm "second"

  out=$(cd "$repo" && "$CHECK" --range HEAD~1..HEAD 2>&1) || status=$?
  expect_code 1 "$status" "a pipeline-driven scan must still fail the run"
  assert_contains "$out" "fleet terminology" "the range scan did not report the violation"
  pass "a violation found in a pipeline stage still fails the command"
}

test_only_added_lines_are_judged() {
  local repo status=0
  repo="$TMP_ROOT/repo-preexisting"
  mkdir -p "$repo"
  git -C "$repo" init -q
  git -C "$repo" config user.email t@example.com
  git -C "$repo" config user.name Tester
  # Pre-existing offending text, committed before the check existed.
  printf 'the captain approved this\n' > "$repo/legacy.txt"
  git -C "$repo" add legacy.txt
  git -C "$repo" commit -qm "legacy"
  printf 'the captain approved this\nan unrelated clean line\n' > "$repo/legacy.txt"
  git -C "$repo" add legacy.txt
  git -C "$repo" commit -qm "add a clean line"

  (cd "$repo" && "$CHECK" --range HEAD~1..HEAD >/dev/null 2>&1) || status=$?
  expect_code 0 "$status" \
    "pre-existing text must not block an unrelated clean change"
  pass "only added lines are judged, so legacy text does not block new work"
}

test_agent_coauthor_trailer_is_rejected
test_generated_by_footer_is_rejected
test_fleet_terminology_is_rejected
test_tracker_ids_are_rejected
test_ordinary_project_text_is_accepted
test_verdict_survives_the_pipeline
test_only_added_lines_are_judged
