#!/usr/bin/env bash
# Behavior tests for fm-spawn.sh's PR-base / epic-gitflow gate (gflow-04).
#
# The gate lives in the ship delivery-agreement block, before any backend launch.
# These tests drive real briefs (generated by the real fm-brief.sh so the
# brief->spawn wiring is exercised end to end), a real isolated git worktree with
# a local bare origin, and the same fake tmux the other spawn suites use: it
# reports the pane cwd and captures the launch command sent with `send-keys -l`,
# so a successful spawn is proven by a non-empty launch log and its refusal by an
# empty one, without starting any real harness.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

SPAWN="$ROOT/bin/fm-spawn.sh"
BRIEF="$ROOT/bin/fm-brief.sh"
TMP_ROOT=$(fm_test_tmproot fm-spawn-base)

# Minimal fake toolchain: a tmux that answers the pane/probe queries and logs the
# literal launch command, plus treehouse/timeout passthroughs. Copied from the
# established spawn-suite pattern (tests/fm-spawn-dispatch-profile.test.sh).
make_base_fakebin() {
  local dir=$1 fakebin
  fakebin=$(fm_fakebin "$dir")
  cat > "$fakebin/tmux" <<'SH'
#!/usr/bin/env bash
set -u
case "$*" in
  *"#{pane_current_path}"*) printf '%s\n' "${FM_FAKE_PANE_PATH:-}"; exit 0 ;;
esac
case "${1:-}" in
  display-message) printf 'firstmate\n'; exit 0 ;;
  list-windows) exit 0 ;;
  has-session|new-session|new-window|kill-window) exit 0 ;;
  send-keys)
    if [ -n "${FM_FAKE_LAUNCH_LOG:-}" ]; then
      prev=
      for a in "$@"; do
        [ "$prev" = "-l" ] && printf '%s\n' "$a" >> "$FM_FAKE_LAUNCH_LOG"
        prev=$a
      done
    fi
    exit 0
    ;;
esac
exit 0
SH
  chmod +x "$fakebin/tmux"
  fm_fake_exit0 "$fakebin" treehouse
  # timeout is deliberately NOT stubbed: fm-epic-branch.sh bounds its git calls
  # through fm_run_timed, which invokes `timeout -k 1 <s> ...`; a naive shift/exec
  # stub mis-parses that form. The real bounded-run mechanism handles it.
  printf '%s\n' "$fakebin"
}

# make_base_case <name> <mode> [--base <branch>]: build a home + project (real
# worktree + bare origin), scaffold a REAL ship brief with the given mode/base,
# and echo "case_dir|home|proj|wt|fakebin|launchlog|id".
make_base_case() {
  local name=$1 mode=$2; shift 2
  local case_dir home proj wt fakebin launchlog id
  case_dir="$TMP_ROOT/$name"
  home="$case_dir/home"
  proj="$case_dir/project"
  wt="$case_dir/wt"
  launchlog="$case_dir/launch.log"
  id="base-$name-t1"
  fakebin=$(make_base_fakebin "$case_dir/fake")
  mkdir -p "$home/data" "$home/projects" "$home/state" "$home/config"
  printf 'claude\n' > "$home/config/crew-harness"
  fm_git_worktree "$proj" "$wt" "wt-$name"
  touch "$home/state/.last-watcher-beat"
  FM_ROOT_OVERRIDE="$ROOT" FM_HOME="$home" \
    FM_DATA_OVERRIDE="$home/data" FM_STATE_OVERRIDE="$home/state" \
    "$BRIEF" "$id" "$(basename "$proj")" --mode "$mode" "$@" >/dev/null
  printf '%s\n' "$case_dir|$home|$proj|$wt|$fakebin|$launchlog|$id"
}

read_base_case() {
  # CASE_DIR is parsed for record symmetry with the other spawn suites but this
  # suite drives everything through the named home/proj/wt fields instead.
  # shellcheck disable=SC2034
  IFS='|' read -r CASE_DIR HOME_DIR PROJ_DIR WT_DIR FAKEBIN_DIR LAUNCH_LOG ID <<EOF
$1
EOF
}

# Push a branch to the project's bare origin so fm-epic-branch.sh verify finds it.
push_epic_branch() {
  local proj=$1 slug=$2
  git -C "$proj" push -q origin "HEAD:refs/heads/epic/$slug"
}

run_base_spawn() {
  local home=$1 wt=$2 fakebin=$3 launchlog=$4
  shift 4
  : > "$launchlog"
  FM_ROOT_OVERRIDE='' FM_HOME="$home" \
    FM_STATE_OVERRIDE="$home/state" FM_DATA_OVERRIDE="$home/data" \
    FM_PROJECTS_OVERRIDE="$home/projects" FM_CONFIG_OVERRIDE="$home/config" \
    FM_SPAWN_NO_GUARD=1 FM_FAKE_PANE_PATH="$wt" TMUX="fake,1,0" \
    CLAUDE_CONFIG_DIR="" FM_FAKE_LAUNCH_LOG="$launchlog" \
    PATH="$fakebin:$PATH" \
    "$SPAWN" "$@" 2>&1
}

# --- refusal: epic story spawned without --base -----------------------------
test_epic_story_without_base_is_refused() {
  local rec out status
  rec=$(make_base_case epic-nobase direct-PR --base epic/gflow)
  read_base_case "$rec"
  push_epic_branch "$PROJ_DIR" gflow
  out=$(run_base_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" \
    "$ID" "$PROJ_DIR" --mode direct-PR --yolo off)
  status=$?
  expect_code 1 "$status" "epic story spawned without --base must refuse"
  assert_contains "$out" "passed no --base" "refusal must name the missing --base"
  assert_contains "$out" "epic/gflow" "refusal must name the epic base"
  [ ! -s "$LAUNCH_LOG" ] || fail "refused epic spawn must not launch (launch log non-empty)"
  pass "epic story spawned without --base is refused before launch"
}

# --- refusal: epic base whose branch does not exist -------------------------
test_epic_base_missing_branch_is_refused() {
  local rec out status
  rec=$(make_base_case epic-missing direct-PR --base epic/ghost)
  read_base_case "$rec"
  # deliberately do NOT push epic/ghost to origin
  out=$(run_base_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" \
    "$ID" "$PROJ_DIR" --mode direct-PR --yolo off --base epic/ghost)
  status=$?
  expect_code 1 "$status" "epic base with a missing branch must refuse (fail closed)"
  assert_contains "$out" "could not confirm it exists" "refusal must explain the missing epic branch"
  [ ! -s "$LAUNCH_LOG" ] || fail "refused missing-branch spawn must not launch"
  pass "epic base whose branch is missing is refused (fail closed)"
}

# --- refusal: spawn --base disagrees with the brief's recorded base ----------
test_base_mismatch_is_refused() {
  local rec out status
  rec=$(make_base_case epic-mismatch direct-PR --base epic/gflow)
  read_base_case "$rec"
  push_epic_branch "$PROJ_DIR" gflow
  out=$(run_base_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" \
    "$ID" "$PROJ_DIR" --mode direct-PR --yolo off --base epic/other)
  status=$?
  expect_code 1 "$status" "a --base disagreeing with the brief must refuse"
  assert_contains "$out" "PR base mismatch" "refusal must name the base drift"
  [ ! -s "$LAUNCH_LOG" ] || fail "mismatched-base spawn must not launch"
  pass "spawn --base disagreeing with the brief's recorded base is refused"
}

# --- success: epic base present + matching --base launches -------------------
test_epic_base_present_launches() {
  local rec out status
  rec=$(make_base_case epic-present direct-PR --base epic/gflow)
  read_base_case "$rec"
  push_epic_branch "$PROJ_DIR" gflow
  out=$(run_base_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" \
    "$ID" "$PROJ_DIR" --mode direct-PR --yolo off --base epic/gflow)
  status=$?
  expect_code 0 "$status" "epic spawn onto an existing epic branch must launch"
  assert_contains "$out" "spawned $ID" "success must report the spawn"
  assert_contains "$out" "base=epic/gflow" "success line must record the epic base"
  [ -s "$LAUNCH_LOG" ] || fail "successful epic spawn must launch (launch log empty)"
  pass "epic story with an existing epic branch and matching --base launches"
}

# --- documented escape: an explicit non-epic base (bootstrap) launches -------
test_bootstrap_non_epic_base_launches_without_epic_verify() {
  local rec out status
  rec=$(make_base_case bootstrap-main direct-PR --base main)
  read_base_case "$rec"
  # No epic branch exists anywhere; a non-epic base must not trigger epic verify.
  out=$(run_base_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" \
    "$ID" "$PROJ_DIR" --mode direct-PR --yolo off --base main)
  status=$?
  expect_code 0 "$status" "an explicit non-epic base is the documented escape and must launch"
  assert_contains "$out" "base=main" "success line must record the explicit base"
  assert_not_contains "$out" "could not confirm it exists" "a non-epic base must skip the epic-existence gate"
  [ -s "$LAUNCH_LOG" ] || fail "bootstrap non-epic base spawn must launch"
  pass "explicit non-epic base (bootstrap escape) launches without an epic-branch check"
}

# --- regression: an ordinary spawn (no base) is unchanged --------------------
test_ordinary_spawn_without_base_is_unchanged() {
  local rec out status
  rec=$(make_base_case ordinary direct-PR)   # no --base -> historical behavior
  read_base_case "$rec"
  assert_no_grep "PR base:" "$HOME_DIR/data/$ID/brief.md" "an ordinary brief must record no PR base line"
  out=$(run_base_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" \
    "$ID" "$PROJ_DIR" --mode direct-PR --yolo off)
  status=$?
  expect_code 0 "$status" "an ordinary spawn with no base must still dispatch"
  assert_contains "$out" "spawned $ID" "ordinary spawn must report the spawn"
  assert_not_contains "$out" "base=" "an ordinary spawn must not report a base"
  [ -s "$LAUNCH_LOG" ] || fail "ordinary spawn must launch"
  pass "ordinary spawn without --base dispatches unchanged (regression)"
}

# --- flag guards: --base rejected on --relaunch and on --scout ---------------
test_base_rejected_on_relaunch() {
  local out status
  out=$(run_base_spawn "$TMP_ROOT" "$TMP_ROOT" "$TMP_ROOT" "$TMP_ROOT/rl.log" \
    any-id --relaunch --base epic/gflow 2>&1)
  status=$?
  expect_code 1 "$status" "--base with --relaunch must be refused"
  assert_contains "$out" "reuses the task's recorded PR base" "relaunch must reject --base"
  pass "--base is rejected on --relaunch"
}

test_base_rejected_on_scout() {
  local rec out status
  rec=$(make_base_case scout-guard direct-PR)
  read_base_case "$rec"
  out=$(run_base_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" \
    "$ID" "$PROJ_DIR" --scout --base epic/gflow)
  status=$?
  expect_code 1 "$status" "--base with --scout must be refused"
  assert_contains "$out" "--base applies only to ship spawns" "scout must reject --base"
  pass "--base is rejected on --scout"
}

test_epic_story_without_base_is_refused
test_epic_base_missing_branch_is_refused
test_base_mismatch_is_refused
test_epic_base_present_launches
test_bootstrap_non_epic_base_launches_without_epic_verify
test_ordinary_spawn_without_base_is_unchanged
test_base_rejected_on_relaunch
test_base_rejected_on_scout

echo "# all fm-spawn-base tests passed"
