defaultPlacement: end
fieldLayouts:
  200548ac-0869-4b2f-b9d5-135b505189ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-15T16:28:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: f845d21f-cf9b-4ab1-a040-8da48debfcfa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-11T13:55:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 333c3c31-89b7-4eff-a855-da3d79bfe667 # Import UID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4267b746-98f6-4258-a047-b5cefcc4ea6d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 665f643b-a13a-4fbe-8774-7dbf3cb27a1e
        userCondition: null
handle: resourceCategory
name: 'Resource Category'
siteSettings:
  a57193b9-dd25-415d-a670-e4b6a0c7b8cb: # $SYSTEM_NAME
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 3b3214ce-0bce-44c9-a288-121f2a26e316
