childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 1bbafb5d-c8cf-4079-bc77-d7454f822431 # Content Builder
fieldLayouts:
  a8c4f6a2-81e2-4f76-9265-adda0cf713cd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-10T19:06:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 56e4d199-12f7-453f-af17-b79dc615088f # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c143d18a-3137-4735-902e-3580df888307
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c376914a-23f8-4ab3-baa9-1133b433bf0d
        userCondition: null
group: 9546349b-883f-4682-b6b5-419da3c477e7 # Content
groupChildBlockTypes: true
handle: text
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
topLevel: false
