import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { registryPaths } from '../lib/paths.mjs';
import { runMemIn, tmpRegistry } from './helpers.mjs';

test('CLI fixture smoke exercises PR-1 verbs on isolated registry only', () => {
  const dir = tmpRegistry();
  let result = runMemIn(dir, ['propose', '--summary', 'Isolated smoke memory', '--body', 'Created only in a disposable registry.', '--keyword', 'smoke', '--project', '*', '--kind', 'dispatch', '--risk-class', 'critical', '--json']);
  assert.equal(result.status, 0, result.stderr);
  const memId = JSON.parse(result.stdout).memId;
  result = runMemIn(dir, ['activate', memId, '--evidence', 'test:cli-smoke', '--method', 'test', '--json']);
  assert.equal(result.status, 0, result.stderr);
  result = runMemIn(dir, ['show', memId, '--chain', '--json']);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(JSON.parse(result.stdout).record.status, 'active');
  result = runMemIn(dir, ['snapshot', '--json']);
  assert.equal(result.status, 0, result.stderr);
  assert.ok(fs.existsSync(JSON.parse(result.stdout).file));
  result = runMemIn(dir, ['audit', '--json']);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(JSON.parse(result.stdout).activeIndex.status, 'current');
  result = runMemIn(dir, ['quarantine', memId, '--reason', 'fixture quarantine', '--json']);
  assert.equal(result.status, 0, result.stderr);
  result = runMemIn(dir, ['update', memId, '--summary', 'Updated while quarantined', '--json']);
  assert.equal(result.status, 0, result.stderr);
  result = runMemIn(dir, ['retire', memId, '--reason', 'fixture retirement', '--json']);
  assert.equal(result.status, 0, result.stderr);
  const second = runMemIn(dir, ['propose', '--summary', 'Replacement smoke memory', '--json']);
  const successor = JSON.parse(second.stdout).memId;
  result = runMemIn(dir, ['activate', successor, '--evidence', 'test:cli-smoke', '--method', 'test', '--json']);
  assert.equal(result.status, 0, result.stderr);
  result = runMemIn(dir, ['supersede', successor, '--successor', memId, '--reason', 'fixture supersession', '--json']);
  assert.equal(result.status, 0, result.stderr);
  assert.ok(fs.readFileSync(registryPaths(dir).registry, 'utf8').includes('Replacement smoke memory'));
});

test('canonical non-mutating fixture can create empty index without production records', () => {
  const dir = tmpRegistry();
  const project = runMemIn(dir, ['project', '--json']);
  assert.equal(project.status, 0, project.stderr);
  const audit = runMemIn(dir, ['audit', '--json']);
  assert.equal(audit.status, 0, audit.stderr);
  const parsed = JSON.parse(audit.stdout);
  assert.equal(parsed.records.total, 0);
  assert.equal(parsed.records.active, 0);
  assert.equal(parsed.activeIndex.status, 'current');
  assert.equal(fs.existsSync(registryPaths(dir).registry), false);
});
