// fm-branch-mod: the firstmate supervision branch as a Claude Code hooks module,
// with one persistent branch agent per session and a text-only classifier ahead
// of it. docs/claude-supervision-branch.md owns the operator contract; this
// header owns the binding's own shape.
//
// The host-independent decision cores live in this mod's lib/ (the canonical
// copies the repo's lib/ symlinks to): the text builders and parses
// (lib/fm-branch-text.ts), the eligible-rows scan orchestration
// (lib/fm-branch-scope.ts), the wake-routing decision (lib/fm-branch-
// routing.ts), the delivery state machine (lib/fm-branch-delivery.ts), the
// monitor guard (lib/fm-branch-monitor.ts), and the session and settlement
// rules (lib/fm-branch-settlement.ts), beside the shared eligibility fold,
// report-sequence, provider-latch, and classifier modules. This
// file is the Claude Code binding: it keeps only what needs the host
// object - the hook registrations, the raw $.agent.spawn / $.tool.call /
// $.process.run wrappers, the $.clock reads, the Monitor task, the env and
// fs seams the validator lists, and the tool.call/turn.step rewrites.
//
//   (a) prompt.submit: the Stop-hook rewake (or the continuity monitor's event)
//       -> eligibility scope -> classifier -> grant -> deliver to the branch
//       -> drop. Delivery is $.agent.spawn once per branch generation, then
//       $.tool.call SendMessage to the same named agent for every later wake.
//   (b) agents/fm-branch.md: bin/fm-branch-prompt.sh plus the hooks-module
//       addendum, generated by bin/fm-branch-agent-md.sh.
//   (c) tool.call rewrite injecting the branch actor identity into Bash.
//   (d) fm_branch_report / fm_branch_processed backed by bin/fm-branch-outcome.sh.
//   (e) turn.complete (branch): release grant, context-bound rotation, the
//       deterministic backstop (bin/fm-wake-evidence.sh --routine-covered) as a
//       main prompt, then route any wake still queued.
//   (f) turn.step effort rewrite for the branch's own agent ids.
// continuity: one Monitor task per session streams each watcher close as a
//       task-notification into prompt.submit; armed at session start when the
//       mode file is present and the session lock is held, on any captain
//       prompt or stop-hook-sourced wake that finds no live monitor (a claim
//       older than the stale bound counts as dead), and from the branch's
//       settlement - never dependent on a captain prompt to exist.
//
// The module refuses to load on any Claude Code version other than CLAUDE_CODE_PIN:
// the version is read from the binary hosting the session (PATH `claude` is only
// the fallback), every hook passes through untouched on a mismatch, and the
// session runs as if the plugin were absent.
//
// Switch (a file under the home's state directory):
//   .branch-mod-mode        present = route wakes; absent = log only, never route.
//                           The same presence switches every bin/ piece the mod relies on.
// Records (same directory):
//   .branch-mod-counters            session counters keyed by the lock pid
//   .branch-mod-passed              queue seqs passed to main with a cover row and not yet acknowledged
//   branch-mod-events.jsonl         append-only event log, size-capped
//   branch-mod-classifications.jsonl  one record per classifier call
import type { On } from 'claude-code'
// The shared cores, imported from this mod's canonical ../lib (the repo's
// lib/ points back at these files through symlinks; the node:fs default
// bindings live in that wrapper, excluded here: this module may import only
// its own files and "claude-code").
import {
  foldVocabularyFromEnv,
  scopeForUnreadWake as libScopeForUnreadWake,
  statusKindFromMetaText,
} from '../lib/fm-branch-eligibility.ts'
import type { FoldVocabulary } from '../lib/fm-branch-eligibility.ts'
import { scanScope, type Scope, type ScopeScanDeps } from '../lib/fm-branch-scope.ts'
import {
  appendFailureMessage,
  markProcessedArgv,
  markReadArgv,
  reportAppendArgv,
  reportSuccessMessage,
  reportTaskScopeVerdict,
  runSettlementStep,
  validateBranchReport,
  validateThroughValue,
} from '../lib/fm-branch-report-sequence.ts'
import {
  classifierPassCoverArgv,
  classifyWake,
  passedToMainSummary,
  type ClassifierResult,
} from '../lib/fm-branch-classifier.ts'
import { createProviderErrorLatch } from '../lib/fm-branch-provider-latch.ts'
import {
  bashActorCommand,
  isStopHookWakeText,
  isVersionShaped,
  newStatusLinesNote as libNewStatusLinesNote,
  parseMonitorEvent,
  processingRequest,
  reasonLines,
  rewakeBanner,
  taskNoticeId,
  toolText,
  versionToken,
} from '../lib/fm-branch-text.ts'
import { createWakeRouter, type InFlight } from '../lib/fm-branch-routing.ts'
import { createBranchDelivery } from '../lib/fm-branch-delivery.ts'
import { createMonitorGuard, MONITOR_DESCRIPTION, MONITOR_TIMEOUT_MS } from '../lib/fm-branch-monitor.ts'
import {
  backstopCheck as libBackstopCheck,
  BRANCH_ROTATE_TOKENS,
  buildCountersText,
  countersApplyVerdict,
  parseCountersRecord,
  rotateDue,
  transcriptPersistenceFromEnv,
  wakeUsageFold,
} from '../lib/fm-branch-settlement.ts'

export const CLAUDE_CODE_PIN = '2.1.278'

type PinCheck = { version: string; source: 'running binary' | 'PATH claude'; probe: string }

const PLUGIN = 'fm-branch-mod'
const REPORT_TOOL = `mcp__${PLUGIN}__fm_branch_report`
const PROCESSED_TOOL = `mcp__${PLUGIN}__fm_branch_processed`
const PROVIDER_ERROR_LATCH_POLICY = {
  threshold: 2,
  baseCooldownMs: 5 * 60 * 1000,
  maxCooldownMs: 5 * 60 * 1000,
  recoveryProbe: false,
}
const EVENT_LOG_CAP_BYTES = 4_000_000
const BOAT = '⛵'
const ANCHOR = '⚓'

let bound = false
let refused = false
let cwd = ''
let home = ''
let state = ''
let config = ''
let bin = ''
let pluginRoot = ''
let generation = ''
let activated = false
let lockPid = ''
// The provider-error latch (counting, cooldown, expiry) is the shared machine.
// What counts as one failure is this host's declared seam: a completed branch
// turn that ended in a provider error or produced no report. Its clock reads
// the host time this module last observed through $.clock.now() - the mockable
// time source in the engine and real time in production - never raw Date.now,
// which the engine's mock clock does not move.
let lastKnownNowMs = Date.now()
const providerLatch = createProviderErrorLatch(PROVIDER_ERROR_LATCH_POLICY, () => lastKnownNowMs)
let wakeCounter = 0
let stepsThisWake = 0

function scriptEnv(extra: Record<string, string> = {}): Record<string, string> {
  return {
    FM_HOME: home,
    FM_STATE_OVERRIDE: state,
    FM_CONFIG_OVERRIDE: config,
    FM_WAKE_QUEUE: `${state}/.wake-queue`,
    FM_WAKE_QUEUE_LOCK: `${state}/.wake-queue.lock`,
    ...extra,
  }
}

function appendLine($: any, path: string, line: string, cap: number): Promise<unknown> {
  // One shell append per record, rotated once past the cap so the log cannot grow without bound.
  const script = 'f=$1; cap=$2; if [ -f "$f" ] && [ "$(wc -c < "$f")" -gt "$cap" ]; then mv -f "$f" "$f.1"; fi; cat >> "$f"'
  return $.process.run(['sh', '-c', script, '_', path, String(cap)], { stdin: line, timeoutMs: 3000 })
}

// Append-only event log: the evidence source for every count the live test asserts.
function log($: any, kind: string, data: unknown): void {
  if (!state) return
  const line = JSON.stringify({ t: new Date().toISOString(), kind, data }) + '\n'
  void appendLine($, `${state}/branch-mod-events.jsonl`, line, EVENT_LOG_CAP_BYTES).catch(() => {})
}

function parentDirectory(path: string): string {
  const cut = path.replace(/\/+$/, '').lastIndexOf('/')
  return cut > 0 ? path.slice(0, cut) : '/'
}

// Home and script resolution follow bin/ exactly: FM_HOME, then FM_ROOT_OVERRIDE,
// then the tracked code root three levels above the plugin folder; state and
// config honour their own overrides; scripts always come from the code root.
export async function bind($: any, sessionCwd: string): Promise<void> {
  if (bound) return
  bound = true
  cwd = sessionCwd
  pluginRoot = $.plugin.root
  const codeRoot = parentDirectory(parentDirectory(parentDirectory(pluginRoot)))
  // Literal names only: strict validation lists the variables a module reads.
  const text = (v: unknown) => String(v ?? '')
  let fmHome = ''
  let fmRoot = ''
  let fmState = ''
  let fmConfig = ''
  try {
    fmHome = text(await $.env.get('FM_HOME'))
    fmRoot = text(await $.env.get('FM_ROOT_OVERRIDE'))
    fmState = text(await $.env.get('FM_STATE_OVERRIDE'))
    fmConfig = text(await $.env.get('FM_CONFIG_OVERRIDE'))
  } catch {}
  home = fmHome || fmRoot || codeRoot
  state = fmState || `${home}/state`
  config = fmConfig || `${home}/config`
  bin = `${codeRoot}/bin`
  if (!generation) generation = `cc${Date.now()}`
}
async function ensureBound($: any): Promise<void> {
  if (bound) return
  await bind($, await $.session.cwd())
  log($, 'rebound', { cwd, generation })
}

async function modeOn($: any): Promise<boolean> {
  return $.fs.exists(`${state}/.branch-mod-mode`)
}
async function readConfig($: any, name: string, fallback: string): Promise<string> {
  try {
    return (await $.fs.read(`${config}/${name}`)).trim() || fallback
  } catch {
    return fallback
  }
}
// Queue rows the classifier already passed to main, durable across a module
// reload or a session restart: while such a row is still queued it goes back
// to main unclassified, because its lines are HISTORY to the classifier now.
async function readPassedSeqs($: any): Promise<Set<string>> {
  try {
    const j = JSON.parse(await $.fs.read(`${state}/.branch-mod-passed`))
    return new Set(Array.isArray(j) ? j.map(String) : [])
  } catch {
    return new Set()
  }
}
async function writePassedSeqs($: any, seqs: Set<string>): Promise<void> {
  try {
    await $.fs.write(`${state}/.branch-mod-passed`, JSON.stringify([...seqs]))
  } catch {}
}
async function readLockPid($: any): Promise<string> {
  try {
    const raw = (await $.fs.read(`${state}/.lock`)).split('\n')[0].trim()
    return /^[0-9]+$/.test(raw) ? raw : ''
  } catch {
    return ''
  }
}

// Session counters survive a module reload (/reload-plugins): the file is
// bound to the session lock pid, so a genuinely new session starts at zero.
// The record shape and the same-lock rule are the settlement module's; this
// binding assembles the fields from the machines that own them.
async function saveCounters($: any): Promise<void> {
  try {
    const d = delivery.snapshot()
    const m = monitorGuard.snapshot()
    await $.fs.write(
      `${state}/.branch-mod-counters`,
      buildCountersText({
        lockPid: lockPid || (await readLockPid($)),
        wakeCounter,
        spawnCount: d.spawnCount,
        sendCount: d.sendCount,
        generation,
        branchGeneration: d.branchGeneration,
        branchRef: d.branchRef,
        branchAgentId: d.branchAgentId,
        monitorTaskId: m.monitorTaskId,
        monitorArmedAt: m.monitorArmedAt,
      }),
    )
  } catch {}
}
async function restoreCounters($: any): Promise<void> {
  try {
    const j = parseCountersRecord(await $.fs.read(`${state}/.branch-mod-counters`))
    const pid = await readLockPid($)
    if (j && countersApplyVerdict(j, pid)) {
      wakeCounter = j.wakeCounter ?? 0
      delivery.restoreFromCounters(j)
      if (j.generation) generation = j.generation
      monitorGuard.restoreFromCounters(j.monitorTaskId, j.monitorArmedAt, Number(await $.clock.now()))
      log($, 'counters.restored', { ...j, reason: 'same session lock pid (module reloaded)' })
    }
  } catch {}
}

async function grant($: any, args: string[], timeoutMs = 5000): Promise<number> {
  const r = await $.process.run(['bash', `${bin}/fm-wake-grant.sh`, ...args], { cwd, env: scriptEnv(), timeoutMs })
  return r.exitCode
}
async function ensureActivated($: any): Promise<boolean> {
  if (activated) return true
  lockPid = await readLockPid($)
  if (!lockPid) return false
  const rc = await grant($, ['activate', lockPid, generation])
  activated = rc === 0
  log($, 'grant.activate', { lockPid, generation, rc })
  return activated
}

// ---- eligibility: the shared fold, bound to the host seam ----

// The FM_CLASSIFY_* names and defaults of bin/fm-classify-lib.sh. The hooks
// host answers $.env.get name by name (no process global in the module
// sandbox, and a literal name at every call site so the host can list the
// variables a module reads), so the four names are read literally and the
// shared lib's defaults rule fills the rest.
async function foldVocabulary($: any): Promise<FoldVocabulary> {
  const [resolveVerb, heldVerb, reservedPrefixes, pausedVerb] = await Promise.all([
    $.env.get('FM_CLASSIFY_RESOLVE_VERB'),
    $.env.get('FM_CLASSIFY_CAPTAIN_HELD_VERB'),
    $.env.get('FM_CLASSIFY_RESERVED_KEY_PREFIXES'),
    $.env.get('FM_CLASSIFY_PAUSED_VERB'),
  ])
  const byName: Record<string, string | undefined> = {
    FM_CLASSIFY_RESOLVE_VERB: resolveVerb === undefined ? undefined : String(resolveVerb),
    FM_CLASSIFY_CAPTAIN_HELD_VERB: heldVerb === undefined ? undefined : String(heldVerb),
    FM_CLASSIFY_RESERVED_KEY_PREFIXES: reservedPrefixes === undefined ? undefined : String(reservedPrefixes),
    FM_CLASSIFY_PAUSED_VERB: pausedVerb === undefined ? undefined : String(pausedVerb),
  }
  return foldVocabularyFromEnv((name) => byName[name])
}

// The scan's IO seam over the host object: the shared scan module owns the
// orchestration (queue read, meta enumeration, kinds, the torn check) and
// the pure fold stays lib/fm-branch-eligibility.ts's, reached through the
// core seam because a module in this lib/ may import nothing.
function scopeScanDeps($: any): ScopeScanDeps {
  return {
    readFile: (path: string) => $.fs.read(path),
    listDir: (path: string) => $.fs.list(path),
    stat: (path: string) => $.fs.stat(path),
    vocabulary: () => foldVocabulary($),
    core: { statusKindFromMetaText, scopeForUnreadWake: libScopeForUnreadWake as ScopeScanDeps['core']['scopeForUnreadWake'] },
  }
}

// The eligible-rows scan, delegated to the shared module. Exported for the
// portable tests (same precedent as serveReport).
export async function scopeForUnreadWake($: any, heartbeat: boolean): Promise<Scope> {
  return scanScope(scopeScanDeps($), state, heartbeat)
}

// Deterministic note of the status lines appended since the task's last
// outcome, through the shared text module. Exported for the portable tests.
export async function newStatusLinesNote($: any, tasks: string[]): Promise<string> {
  return libNewStatusLinesNote({ readFile: (path: string) => $.fs.read(path) }, state, tasks)
}

async function outcome($: any, args: string[]): Promise<{ ok: boolean; stdout: string; detail: string }> {
  const r = await $.process.run(['bash', `${bin}/fm-branch-outcome.sh`, ...args], { cwd, env: scriptEnv(), timeoutMs: 8000 })
  if (r.exitCode === 0) return { ok: true, stdout: r.stdout.trim(), detail: '' }
  return { ok: false, stdout: '', detail: `fm-branch-outcome.sh exited ${r.exitCode}: ${r.stderr.trim()}` }
}

// A registered tool's answer must be a string or content array (core check).
function textResult(text: string, isError = false) {
  return isError ? { deny: text } : { result: text }
}

// ---- the lib/ machines, bound per call to the host object ----
// The validator's spelling rule for $ (always $.noun.event at the call
// site, never held in a variable) is why every machine takes its deps per
// call, exactly as classifierDeps($) always has.

function deliveryDeps($: any) {
  return {
    log: (kind: string, data: unknown) => log($, kind, data),
    sessionTranscriptId: () => sessionTranscriptId($),
    sendMessage: (to: string, prompt: string) => $.tool.call({ tool: 'SendMessage', to, summary: 'fm-branch-mod wake', message: prompt }),
    spawnAgent: (opts: Record<string, unknown>) => $.agent.spawn(opts),
    listAgents: () => $.agent.list(),
    readModel: () => readConfig($, 'supervision-branch-model', 'sonnet'),
    saveCounters: () => saveCounters($),
    toolText,
    pluginName: PLUGIN,
  }
}

const delivery = createBranchDelivery()
const monitorGuard = createMonitorGuard()
const router = createWakeRouter()

function monitorDeps($: any) {
  return {
    log: (kind: string, data: unknown) => log($, kind, data),
    clockNow: async () => Number(await $.clock.now()),
    modeOn: () => modeOn($),
    startMonitor: async (command: string) => {
      const r = await $.tool.call({ tool: 'Monitor', command, description: MONITOR_DESCRIPTION, timeout_ms: MONITOR_TIMEOUT_MS })
      return { text: toolText(r), deny: r?.deny }
    },
    saveCounters: () => saveCounters($),
    paths: () => ({ cwd, home, state, config, bin }),
  }
}

function routerDeps($: any) {
  return {
    log: (kind: string, data: unknown) => log($, kind, data),
    reasonLines,
    clockNow: async () => {
      const now = Number(await $.clock.now())
      lastKnownNowMs = now
      return now
    },
    dateNow: () => Date.now(),
    modeOn: () => modeOn($),
    latched: () => providerLatch.admitWake().decision === 'latched',
    afkPresent: () => $.fs.exists(`${state}/.afk`),
    scopeFor: (heartbeat: boolean) => scopeForUnreadWake($, heartbeat),
    readPassedSeqs: async () => [...(await readPassedSeqs($))],
    writePassedSeqs: (seqs: string[]) => writePassedSeqs($, new Set(seqs)),
    classify: (wake: string, tasks: string[], seqs: string[]) => classify($, wake, tasks, seqs),
    ensureActivated: () => ensureActivated($),
    grantPublish: (seqs: string[]) => grant($, ['publish', generation, ...seqs]),
    grantRelease: () => grant($, ['release', generation]).catch(() => {}),
    advanceEvidence: (task: string) => {
      void $.process.run(['bash', `${bin}/fm-wake-evidence.sh`, task], { cwd, env: scriptEnv(), timeoutMs: 25000 }).catch(() => {})
    },
    runOutcome: (argv: string[]) => outcome($, argv),
    passedToMainSummary,
    classifierPassCoverArgv,
    claimWakeNo: async () => {
      wakeCounter += 1
      await saveCounters($)
      return wakeCounter
    },
    freshAgentNeeded: () => delivery.freshAgentNeeded(),
    stateDir: () => state,
    statusNote: (tasks: string[]) => newStatusLinesNote($, tasks),
    resetStepCounter: () => {
      stepsThisWake = 0
    },
    deliver: (prompt: string) => delivery.deliverToBranch(deliveryDeps($), prompt),
    spawnSendCounts: () => {
      const d = delivery.snapshot()
      return { spawnCount: d.spawnCount, sendCount: d.sendCount }
    },
  }
}

// ---- report and processed tools ----

export async function serveReport($: any, e: any, agentId: string | undefined) {
  const task = String(e.task ?? '').trim()
  const verdict = String(e.verdict ?? '')
  const summary = String(e.summary ?? '').trim()
  const wake = String(e.wake ?? '').trim()
  const silent = e.silent === true
  const p = router.peekInFlight()
  log($, 'report.call', { agentId, task, verdict, summary, silent, wakeNo: p?.wakeNo })
  const validated = validateBranchReport({ task, verdict, summary, silent })
  if (!validated.valid) {
    return textResult(validated.message, true)
  }
  // The task-in-scope rule is the shared module's; this host's refusal wording
  // (the corrective re-report instruction, no row list) is a declared seam.
  const scopeVerdict = reportTaskScopeVerdict(p && !p.heartbeat ? { rows: [], tasks: [...p.tasks] } : null, task)
  if (!scopeVerdict.allowed) {
    return textResult(`report not recorded: task must be ${scopeVerdict.tasks.join(' or ')} (this wake's own task), not '${task}'. Call fm_branch_report again with task=${scopeVerdict.tasks[0]} and the same verdict and summary.`)
  }
  if (p && p.reportedSeqs.length > 0 && !p.heartbeat) {
    log($, 'report.duplicate', { agentId, task, verdict, priorSeqs: p.reportedSeqs })
    return textResult(`already recorded seq ${p.reportedSeqs[p.reportedSeqs.length - 1]} for this wake; one report per wake is enough. Do not report again: run the exact --ack-through command the drain printed and end your turn with the word done.`)
  }
  const args = reportAppendArgv(validated, wake || null, p?.wakeKey && /^[0-9:,]+$/.test(p.wakeKey) ? ['--wake-key', p.wakeKey] : undefined)
  const appended = await runSettlementStep((argv) => outcome($, argv), args)
  if (!appended.ok) return textResult(appendFailureMessage(appended.detail), true)
  const seq = Number(appended.stdout)
  if (p) p.reportedSeqs.push(seq)
  const marked = await runSettlementStep((argv) => outcome($, argv), markReadArgv(seq))
  if (!marked.ok) return textResult(`recorded seq ${seq}, but cursor advancement failed: ${marked.detail}`, true)
  if (verdict === 'routine') {
    if (!silent) $.ui.log(`${BOAT} ${task}: ${summary}`)
    log($, 'deliver.routine', { seq, task, summary, silent, wakeNo: p?.wakeNo })
  } else {
    $.ui.log(`${ANCHOR} [seq ${seq}] ${task}: ${summary}`)
    void $.prompt.submit({ text: processingRequest(seq, task, summary, 'branch verdict captain') }).catch((err: unknown) => log($, 'deliver.captain.error', { seq, error: String(err) }))
    log($, 'deliver.captain', { seq, task, summary, wakeNo: p?.wakeNo })
  }
  return textResult(reportSuccessMessage(seq, validated.verdict))
}

export async function serveProcessed($: any, e: any) {
  const through = Number(e.through)
  if (!validateThroughValue(through)) return textResult('through must be a positive integer', true)
  const r = await runSettlementStep((argv) => outcome($, argv), markProcessedArgv(through))
  log($, 'processed.call', { through, ok: r.ok, detail: r.ok ? '' : r.detail })
  if (!r.ok) return textResult(`processed marker not advanced: ${r.detail}`, true)
  return textResult(`captain outcomes through seq ${through} marked processed`)
}

// Behavior-neutral test seams (same precedent as scopeForUnreadWake): the
// portable equivalence tests drive the real handlers and plant the in-flight
// wake record the scoping rule reads (tests/fm-branch-report-sequence.test.sh).
export function __fmSetInFlight(p: InFlight | null): void {
  router.setInFlightForTest(p)
}

// Route one watcher wake through the shared routing machine. Exported for
// the portable tests (tests/fm-branch-routing.test.sh).
export async function routeWake($: any, wakeText: string, source: string): Promise<'dropped' | 'passed'> {
  return router.routeWake(routerDeps($), wakeText, source)
}

// ---- classifier ahead of the branch ----
// The classifier core - the evidence byte-range parse and failure text of
// bin/fm-wake-evidence.sh, the prompt construction, the answer
// interpretation rule, and the durable record shape - is the shared module
// (the canonical copy under ../lib, which the repo's lib/ symlinks to); this
// host binds its seams. Exported for the portable tests (same precedent as serveReport).
function classifierDeps($: any) {
  return {
    paths: { bin },
    runScript: (argv: string[], opts: { timeoutMs: number }) => $.process.run(argv, { cwd, env: scriptEnv(), timeoutMs: opts.timeoutMs }),
    readSystemPrompt: () => $.fs.read(`${pluginRoot}/classifier-system.txt`),
    // The explicit classifier-model line wins; this host's default is
    // haiku, also the one-shot fallback when a configured name does not
    // resolve. The shared module resolves configured-wins-then-default
    // before any completion call.
    readConfiguredModel: async () => (await readConfig($, 'classifier-model', '')) || null,
    readDefaultModel: async () => 'haiku',
    complete: async (req: { model: string; system: string; prompt: string; maxTokens: number }) => String(await $.model.complete(req)),
    clock: { now: () => Date.now(), iso: () => new Date().toISOString() },
  }
}

export async function classify($: any, reason: string, tasks: string[], seqs: string[]): Promise<ClassifierResult> {
  const { result, recordLine } = await classifyWake(classifierDeps($), { wake: reason, tasks, seqs })
  // The durable classification log: one record per call, scored later by
  // bin/fm-branch-classifier-score.sh against the status lines main had to act on.
  try {
    await appendLine($, `${state}/branch-mod-classifications.jsonl`, recordLine, EVENT_LOG_CAP_BYTES)
  } catch (error) {
    log($, 'classifier.log.error', { error: String(error) })
  }
  return result
}

// ---- continuity monitor, through the shared guard ----

// Exported for the portable tests (tests/fm-branch-monitor.test.sh).
export function armMonitor($: any, why: string): Promise<void> {
  return monitorGuard.armMonitor(monitorDeps($), why)
}

// Turn a monitor event notification into the Stop hook's banner shape, or
// null when the text is not one of ours / carries no actionable reason.
function monitorEventBanner($: any, text: string): { banner: string | null; ours: boolean; expired: boolean } {
  const parsed = parseMonitorEvent(text, MONITOR_DESCRIPTION)
  if (!parsed.ours) return { banner: null, ours: false, expired: false }
  log($, 'monitor.event', { reasons: parsed.reasons, expired: parsed.expired, text: text.slice(0, 500) })
  return { banner: parsed.reasons.length ? rewakeBanner(parsed.reasons.join('\n')) : null, ours: true, expired: parsed.expired }
}

// ---- deterministic backstop, through the shared settlement module ----

// Exported for the portable tests (tests/fm-branch-settlement.test.sh).
export function backstopCheck($: any, tasks: Set<string>, wakeNo: number): Promise<void> {
  return libBackstopCheck(
    {
      log: (kind, data) => log($, kind, data),
      runCovered: (task) => $.process.run(['bash', `${bin}/fm-wake-evidence.sh`, '--routine-covered', task], { cwd, env: scriptEnv(), timeoutMs: 15000 }),
      submitPrompt: (text) => $.prompt.submit({ text }),
    },
    tasks,
    wakeNo,
  )
}

// ---- the version pin ----

// The version pin: the module is measured against one Claude Code release and
// refuses every other one, so a silent engine change cannot reroute wakes.
// The binary actually hosting this session decides: the launcher execs the
// pinned release by absolute path to survive the installer symlink moving, so
// PATH can name a different release than the one running here. The probe runs
// the host binary's own `--version` through /proc (Linux only); the PATH call
// stays as the fallback, and a probe answer without a version shape is treated
// as unavailable so a misresolved executable can never cause a false refusal.
// The answer names which source decided and the probe's raw output, so a split
// between the two is one log line.
async function checkPin($: any): Promise<PinCheck> {
  let probe = ''
  try {
    const r = await $.process.run(['sh', '-c', 'exec "$(readlink /proc/$PPID/exe)" --version'], { timeoutMs: 10000 })
    probe = String(r.stdout ?? '').trim().slice(0, 200)
    const version = versionToken(probe)
    if (isVersionShaped(version)) return { version, source: 'running binary', probe }
  } catch (error) {
    probe = `unreadable (${String(error)})`
  }
  try {
    const r = await $.process.run(['claude', '--version'], { timeoutMs: 10000 })
    return { version: versionToken(String(r.stdout ?? '').trim()), source: 'PATH claude', probe }
  } catch (error) {
    return { version: `unreadable (${String(error)})`, source: 'PATH claude', probe }
  }
}

// Row 3 of the branch-reuse RCA (2026-09-19): the next transcript regression
// must be one log line instead of a scout. The rule is the settlement
// module's; this binding reads the two environment names literally (strict
// validation lists the variables a module reads).
async function transcriptPersistence($: any): Promise<{ on: boolean; cause: string }> {
  let force = ''
  let marker = ''
  try {
    force = String(await $.env.get('CLAUDE_CODE_FORCE_SESSION_PERSISTENCE') ?? '')
  } catch {}
  try {
    marker = String(await $.env.get('CLAUDE_CODE_CHILD_SESSION') ?? '')
  } catch {}
  return transcriptPersistenceFromEnv(force, marker)
}

// The primary session's transcript id: resume reads the branch agent's
// transcript under it (<session>/subagents/agent-<id>.jsonl), so a send log
// naming both is the resume target the next regression needs; where the engine
// does not expose it the reason is logged in its place.
async function sessionTranscriptId($: any): Promise<string> {
  try {
    return String(await $.session.id() ?? '')
  } catch (error) {
    return `unavailable (${String(error)})`
  }
}

export function register(on: On) {
  on('session.start', async ($, e, next) => {
    await bind($, e.cwd)
    const { version, source: pinSource, probe } = await checkPin($)
    if (version !== CLAUDE_CODE_PIN) {
      refused = true
      $.ui.log(`${PLUGIN}: refusing to load on Claude Code ${version || 'unknown'} (${pinSource}); built for ${CLAUDE_CODE_PIN}`)
      log($, 'pin.refused', { version, pin: CLAUDE_CODE_PIN, pinSource, probe })
      return next(e)
    }
    const persistence = await transcriptPersistence($)
    refused = false
    generation = `cc${Date.now()}`
    activated = false
    router.resetForSession()
    delivery.resetForSession()
    wakeCounter = 0
    monitorGuard.resetForSession()
    await restoreCounters($)
    // Continuity must not wait for a captain prompt: a module reload followed
    // by silence left no Monitor at all, so a Stop-hook-sourced wake the branch
    // absorbed never re-armed one and supervision went dark. Arm at session
    // start when the mode file is present and this session holds the lock - the
    // same evidence restoreCounters reads, never a new lock mechanism.
    // armMonitor's own claim keeps a restored live monitor from double-arming.
    const mode = await modeOn($)
    const lockPidNow = await readLockPid($)
    if (mode && lockPidNow) void armMonitor($, 'session start')
    else log($, 'monitor.skipped', { why: 'session start', mode, lockPid: lockPidNow })
    try {
      await $.tool.register({
        name: 'fm_branch_report',
        description:
          'Record the outcome of one handled fleet event: writes it durably to the outcome store, then merges it into the captain-facing main conversation. verdict captain opens one processing turn on main; routine notes render without a main turn. Call exactly once per handled event.',
        inputSchema: {
          type: 'object',
          properties: {
            task: { type: 'string', description: "The task id the event belongs to (or 'fleet' for fleet-wide events)" },
            verdict: { type: 'string', enum: ['routine', 'captain'], description: 'Use captain or routine exactly as the "Verdict: routine or captain" section of your system prompt decides.' },
            summary: { type: 'string', description: 'One or two sentences in captain outcome language; include the full https:// PR URL when a PR is involved' },
            wake: { type: 'string', description: 'The wake reason line this outcome answers' },
            silent: { type: 'boolean', description: 'True only when a fleet-wide heartbeat review found literally nothing worth reporting' },
          },
          required: ['task', 'verdict', 'summary'],
        },
      })
      await $.tool.register({
        name: 'fm_branch_processed',
        description: 'Main only: acknowledge that every supervision-branch captain outcome up to and including sequence `through` has been processed. Closes the processing request.',
        inputSchema: { type: 'object', properties: { through: { type: 'number' } }, required: ['through'] },
      })
    } catch (error) {
      log($, 'tool.register.error', { error: String(error) })
    }
    const enabled = await modeOn($)
    $.ui.log(`${PLUGIN}: loaded (${enabled ? 'enabled' : 'inert: no state/.branch-mod-mode'}, home ${home}, Claude Code ${version})`)
    log($, 'session.start', { cwd, home, state, enabled, generation, version, pinSource, probe, persistenceOn: persistence.on, persistenceCause: persistence.cause })
    return next(e)
  }).catch(($, e, next) => next(e))

  on('turn.start', async ($, e, next) => {
    if (refused) return next(e)
    await ensureBound($)
    log($, 'turn.start', { turnId: e.turnId, text: e.text.slice(0, 300) })
    return next(e)
  })

  on('prompt.submit', async ($, e, next) => {
    if (refused) return next(e)
    await ensureBound($)
    const kind = e.origin?.kind
    if (kind === 'peer') {
      const m = e.text.match(/<agent-message from="([^"]+)"/)
      const from = m?.[1] ?? ''
      if (delivery.isOwnHandback(from, e.text)) {
        log($, 'handback.dropped', { from, text: e.text.slice(0, 300) })
        return { drop: `${PLUGIN}: branch hand-back suppressed` }
      }
      log($, 'prompt.submit.peer', { origin: e.origin, text: e.text.slice(0, 300) })
      return next(e)
    }
    if (kind !== 'task-notification') {
      log($, 'prompt.submit', { origin: e.origin, text: e.text.slice(0, 200) })
      // First captain prompt of the session: arm continuity from a hook frame.
      if (await modeOn($)) void armMonitor($, 'first prompt')
      return next(e)
    }
    const mon = monitorEventBanner($, e.text)
    if (mon.ours) {
      if (mon.expired) {
        // Only the live monitor's own end re-arms: an older monitor's expiry
        // (after a reload reset this state) must not start a second loop.
        const tid = taskNoticeId(e.text)
        const verdict = monitorGuard.noteExpiry(tid)
        if (verdict.rearm) void armMonitor($, 'monitor expired')
        else log($, 'monitor.stale.expiry', { tid, live: verdict.live })
      }
      if (!mon.banner) return { drop: `${PLUGIN}: monitor notice without a wake` }
      const verdict = await routeWake($, mon.banner, 'monitor')
      if (verdict === 'dropped') return { drop: `${PLUGIN}: routed to supervision branch` }
      return next({ ...e, text: mon.banner })
    }
    // A completed background agent's own notification (ours) must not open a main turn.
    if (delivery.isOwnAgentNotification(e.text)) {
      log($, 'agent.notification.dropped', { text: e.text.slice(0, 300) })
      return { drop: `${PLUGIN}: branch agent notification suppressed` }
    }
    const isWake = isStopHookWakeText(e.text)
    log($, 'prompt.submit', { origin: e.origin, isWake, text: e.text.slice(0, 600) })
    if (!isWake) return next(e)
    // A wake main's own Stop hook produced must always leave one live cycle
    // behind. If the armed claim is false with no expiry notice in hand (a
    // failed arm, a lost notice), arm here so the next watcher close still
    // surfaces; armMonitor's armed/arming claim is the double-arm guard.
    void armMonitor($, 'stop-hook wake without monitor')
    const verdict = await routeWake($, e.text, 'stop-hook')
    if (verdict === 'dropped') return { drop: `${PLUGIN}: routed to supervision branch` }
    return next(e)
  }).catch(($, e, next) => {
    log($, 'prompt.submit.catch', { text: e.text.slice(0, 200) })
    return next(e)
  })

  // ---- (c) Bash actor rewrite and tool denial for the branch ----
  on('tool.call', async ($, e, next) => {
    if (refused) return next(e)
    await ensureBound($)
    const agentId = (e as { agentId?: string }).agentId
    if (agentId && delivery.knowsAgent(agentId)) {
      if (e.tool === 'Bash') {
        const holder = lockPid || (await readLockPid($))
        log($, 'tool.call.bash', { agentId, wakeNo: router.peekInFlight()?.wakeNo, command: String((e as any).command).slice(0, 300) })
        return next({ ...e, command: bashActorCommand(String((e as any).command), holder, { home, state, config }) })
      }
      if (e.tool !== REPORT_TOOL) {
        log($, 'tool.call.denied', { agentId, tool: e.tool })
        return { deny: `${PLUGIN}: the supervision branch may only use Bash and fm_branch_report` }
      }
    } else if (agentId && e.tool === REPORT_TOOL) {
      // Only the branch has this tool: an unknown caller is the branch under a new id.
      log($, 'agent.id.adopted', { agentId, via: 'report tool' })
      delivery.adoptAgent(agentId)
    } else if (agentId && e.tool === 'Bash' && !delivery.knowsAgent(agentId) && delivery.currentAgentId()) {
      // A Bash call from an unknown subagent while our branch is the only
      // subagent we ever spawn is the branch under a new id (SendMessage resume).
      const id = await delivery.resolveNamedAgent(deliveryDeps($))
      log($, 'tool.call.unknown-agent', { agentId, resolved: id })
      if (id === agentId) {
        delivery.adoptAgent(agentId)
        const holder = lockPid || (await readLockPid($))
        return next({ ...e, command: bashActorCommand(String((e as any).command), holder, { home, state, config }) })
      }
    }
    if (e.tool === REPORT_TOOL) return serveReport($, e as any, agentId)
    if (e.tool === PROCESSED_TOOL) return serveProcessed($, e as any)
    return next(e)
  }).catch(($, e, next) => next(e))

  // ---- (f) effort rewrite for the branch's own agent ids ----
  on('turn.step', async function* ($, e, next) {
    if (refused) return yield* next(e)
    const agentId = (e as { agentId?: string }).agentId
    if (agentId && delivery.knowsAgent(agentId)) {
      stepsThisWake += 1
      log($, 'turn.step', { agentId, wakeNo: router.peekInFlight()?.wakeNo, model: e.model, index: e.index, effort: e.effort, messageCount: e.messageCount })
      return yield* next({ ...e, effort: 'low' })
    }
    return yield* next(e)
  })

  on('session.compact', async ($, e, next) => {
    if (refused) return next(e)
    await ensureBound($)
    log($, 'session.compact', { agentId: (e as any).agentId, wakeNo: router.peekInFlight()?.wakeNo })
    return next(e)
  }).catch(($, e, next) => next(e))

  // ---- (e) settlement ----
  on('turn.complete', async ($, e, next) => {
    if (refused) return next(e)
    await ensureBound($)
    const agentId = e.agentId
    if (!agentId) {
      log($, 'turn.complete.main', { reason: e.reason, usage: e.usage })
      return next(e)
    }
    if (!delivery.knowsAgent(agentId)) {
      log($, 'turn.complete.other', { agentId, reason: e.reason, usage: e.usage })
      return next(e)
    }
    const p = router.peekInFlight()
    const { wakeTokens, stepContext } = wakeUsageFold((e.usage ?? {}) as Record<string, number>, stepsThisWake)
    log($, 'turn.complete.branch', {
      agentId,
      wakeNo: p?.wakeNo,
      via: p?.via,
      reason: e.reason,
      usage: e.usage,
      wakeTokens,
      steps: stepsThisWake,
      stepContext,
      elapsedMs: p ? Date.now() - p.startedAt : undefined,
      reportedSeqs: p?.reportedSeqs,
      wake: p?.reason,
      answer: e.answer.slice(0, 400),
    })
    if (rotateDue(stepContext, delivery.isRotatePending())) {
      // The bound lives here, in the mod, not in an autoCompactWindow setting.
      delivery.setRotatePending(true)
      $.ui.log(`${PLUGIN}: branch context reached ${stepContext} tokens a step (> ${BRANCH_ROTATE_TOKENS}); the next wake opens a fresh branch agent`)
      log($, 'rotate.pending', { wakeNo: p?.wakeNo, wakeTokens, stepContext, branchGeneration: delivery.branchGeneration() })
    }
    if (!p) return next(e)
    router.clearInFlight()
    lastKnownNowMs = Number(await $.clock.now())
    const providerError = e.reason === 'error' || e.reason === 'refusal'
    const noReport = p.reportedSeqs.length === 0
    if (p.granted) await grant($, ['release', generation]).catch(() => {})
    if (providerError || noReport) {
      const verdict = providerLatch.recordFailure()
      if (verdict.armed) {
        $.ui.log(`${PLUGIN}: branch latched off for 5 minutes after ${verdict.streak} consecutive failures; wakes go to main`)
      }
      log($, 'branch.failed', { agentId, wakeNo: p.wakeNo, providerError, noReport, consecutiveErrors: verdict.streak, latchedUntil: verdict.latchedUntil })
      router.forgetHandled(p.seqs)
      void $.prompt.submit({ text: `fm-branch-mod: fallback to main - the supervision branch could not handle this wake.\n${p.wakeText}` }).catch(() => {})
    } else {
      providerLatch.recordSuccess()
      // Deterministic captain-class backstop over what the branch just covered.
      await backstopCheck($, p.tasks, p.wakeNo)
    }
    // A branch-absorbed wake must always leave one live cycle behind: if the
    // branch settled a wake and no monitor is armed, arm one here so the next
    // watcher close still reaches a prompt.
    if (!monitorGuard.isArmed()) void armMonitor($, 'branch settled without monitor')
    // Anything that arrived while the branch was busy is still in the queue.
    const scope = await scopeForUnreadWake($, false)
    if (router.hasUnhandled(scope.eligibleSeqs)) {
      log($, 'wake.requeue', { seqs: scope.eligibleSeqs })
      await routeWake($, rewakeBanner(scope.eligibleSeqs.map((s) => `signal: queued row ${s} (re-scoped after branch settlement)`).join('\n')), 'post-release')
    }
    return next(e)
  }).catch(($, e, next) => next(e))
}
