columnSuffix: null
handle: altText2
instructions: 'This will default to the image title if left empty'
name: 'Thumbnail - Thumbnail - Alt Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
