columnSuffix: null
handle: byline
instructions: null
name: Byline
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Name
            -
              - handle
              - name
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Position
            -
              - handle
              - position
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: 1
  minRows: 1
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
