columnSuffix: null
handle: color3
instructions: null
name: 'Overlay Background Properties - Background Color - Color'
searchable: true
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
