columnSuffix: null
handle: darkGrayColor
instructions: null
name: 'Dark Gray Color'
searchable: true
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: site
type: craft\fields\Color
