columnSuffix: null
handle: faq
instructions: null
name: FAQ
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:032f8148-4f97-463b-8b6f-e054ad161659' # FAQs
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
