columnSuffix: null
handle: initiativesPriorities
instructions: null
name: 'Initiatives & Priorities'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:0ce23799-ae33-447a-81d3-4da8649e0cb2'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
