columnSuffix: null
handle: lightGrayColor
instructions: null
name: 'Light Gray Color'
searchable: true
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: site
type: craft\fields\Color
