columnSuffix: sxlbzorf
handle: showPagination
instructions: null
name: 'Show Pagination'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
