columnSuffix: null
handle: show
instructions: null
name: Show
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a show'
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:065fb4c9-a3c6-4058-8d4a-6a86c04330cb'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
