columnSuffix: null
handle: topNavigationLinkColor
instructions: null
name: 'Top Navigation Link Color'
searchable: true
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: site
type: craft\fields\Color
