color: null
fieldLayouts:
  6cf5e28a-97ef-4bad-ab64-68246d1295d2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-10T19:06:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2c82b616-b5b1-45dc-b8fc-bcc9ca094d88
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T19:06:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b91a2c9d-bfc2-4db4-8de8-d17d8a96be25 # Link Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e82132f4-9717-4699-9bca-f987d61e312c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T19:06:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b0b239bd-fc22-43fb-a2de-5f961ce16e9f # Internal Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7101006-4f9b-4de9-af7e-f23c5e2c3ed5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T19:06:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 793742e6-5144-452b-8c7e-acda356b9225 # External Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23790b97-f387-4cab-b0b1-73bee84498f8
            userCondition: null
            warning: null
            width: 100
        name: 'Web Link'
        uid: ac34557e-3e79-4a51-9c6e-4c828fa844c4
        userCondition: null
handle: webLink
hasTitleField: true
icon: null
name: 'Web Link'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
