defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f8bfe787-945c-49f2-a5df-fc24a67e3aac # FAQs
handle: faqs
maxAuthors: 1
name: FAQs
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  a57193b9-dd25-415d-a670-e4b6a0c7b8cb: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
